Repository ymcatwincities/openy_gated_content, pull requests merged in 2020-08, with the labels that each got.

#14 [DONOTMERGE] Add Virtual YMCA Editor role and change admin menu access
  config/install/system.action.user_add_role_action.virtual_ymca_editor.yml
  config/install/system.action.user_remove_role_action.virtual_ymca_editor.yml
  config/install/user.role.virtual_ymca_editor.yml
  openy_gated_content.permissions.yml
  openy_gated_content.routing.yml
Labels: FIVEJARS, NEEDS REVIEW, NEEDS TESTING

#16 Hotfix: removed file_entity module from dependencies
  composer.json
  modules/openy_gc_log/config/install/file_entity.type.archive.yml
  modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
  modules/openy_gc_log/openy_gc_log.info.yml
  modules/openy_gc_log/openy_gc_log.links.menu.yml
  modules/openy_gc_log/openy_gc_log.permissions.yml
  modules/openy_gc_log/openy_gc_log.services.yml
  modules/openy_gc_log/src/LogArchiver.php
  modules/openy_gc_log/src/LogEntityAccessControlHandler.php
Labels: TESTED, bug

#23 Backport of the strtolower fix
  modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
Labels: NEEDS REVIEW

#22 Enable vanity zoom urls.
  js/gated-content/dist/gated-content.umd.min.js
  js/gated-content/src/views/VirtualMeetingPage.vue
Labels: REVIEW, TESTED
